process.env.SUPABASE_URL="https://fjbavwqvjofpioyzfbmo.supabase.co"
process.env.SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqYmF2d3F2am9mcGlveXpmYm1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDc3Njc2NjksImV4cCI6MjAyMzM0MzY2OX0.ZpO4cEUhQPnoq9VeTO97V9JsdW2epjZ3K_Exs49flkg"
process.env.HUGGING_FACE_AUTH="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"